
---
- name: VM playbook
  hosts: localhost
  gather_facts: false
  collections:
    - nutanix.ncp
  module_defaults:
    group/nutanix.ncp.ntnx:
      nutanix_host: 10.38.14.137
      nutanix_username: admin
      nutanix_password: nx2Tech1234*
      validate_certs: false
  tasks:
  - name: Setting Variables
    set_fact:
        cluster_name: "PHX-SPOC014-3"
        script_path: ""
        subnet_name: "primary"
        image_name: "ubuntu-VM"
        password: "Password1234*"
        fqdn: "MyUbuntu"

  - name: Create Cloud-init Script file
    copy:
      dest: "cloud_init.yml"
      content: |
         #cloud-config
         chpasswd:
           list: |
             root: "{{ password }}"
             expire: False
         fqdn: "{{ fqdn }}"

  - name: create Vm
    ntnx_vms:
      state: present
      name: "VM_VD_Ansible"
      desc: "ansible_vm_description"
      categories:
        AppType:
          - "Apache_Spark"
      cluster:
        name: "{{cluster_name}}"
      networks:
        - is_connected: True
          subnet:
            name: "{{ subnet_name }}"
            cluster:
              name: "{{cluster_name}}"
      disks:
        - type: "DISK"
          size_gb: 100
          bus: "SATA"
          clone_image:
            name: "{{ image_name }}"
      vcpus: 1
      cores_per_vcpu: 1
      memory_gb: 1
      guest_customization:
        type: "cloud_init"
        script_path: "./cloud_init.yml"
        is_overridable: True
    register: output

  - name: output of vm created
    debug:
      msg: '{{ output }}'

